Repository bcgov/nr-forests-access-management, pull requests merged in 2023-06, with the labels that each got.

#664 ci: coverage for main merge
  .github/workflows/sonar.yml
  .gitignore
  server/auth_function/.coveragerc
  server/auth_function/lambda_function.py
Labels: enhancement

#666 ci: #87 coverage for PRs
  .github/workflows/sonar.yml
  server/auth_function/.coveragerc
Labels: enhancement

#643 chore(deps): update vitest monorepo to ^0.32.0
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#671 chore(deps): update dependency fastapi to v0.98.0
  server/backend/requirements.txt
Labels: bug

#669 ci: sonar adjustments and fixes
  .github/workflows/sonar.yml
  server/auth_function/.coveragerc
  server/auth_function/lambda_function.py
  server/backend/.coveragerc
  server/backend/requirements.txt
Labels: bug, enhancement

#674 ci: adjust sonar for auth
  .github/workflows/sonar.yml
  frontend/vite.config.ts
  server/auth_function/.coveragerc
  server/backend/.coveragerc
Labels: bug
